[Database]
Host ="127.0.0.1:3306"
Type ="mysql"
User ="root"
Pwd ="835264630Yy@"
Name ="sport"

[Server]
HttpPort="8088"
Key=""
JwtHeader="Authorization"
#以分钟为单位
TokenExpireTime=30
TokenSecretKey="47d48038-5c85-468a-b17c-ba06bf669c39"
[Log]
LogPath ="/var/log"
LogFile="supersport.log"
Level="debug"

[Redis]
Host ="127.0.0.1:6379"
User ="root"
Pwd =""

